services:
  redis:
    image: 'docker.io/redis:7-alpine'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server /redis.conf
    volumes:
      - './redis/redis.conf:/redis.conf'
      - './redis/data:/data'
    # To match in config_prod.json or rsplace_sever env with redis://rsplace_redis/
    hostname: rsplace_redis
    container_name: rsplace_redis
  place:
    image: 'rs-place:dev'
    restart: always
    ports:
      - '80:80'
    volumes:
      - './config_prod.json:/config.json'
    environment:
      - REDIS_URL=redis://rsplace_redis/
      - HOST=0.0.0.0
      - PORT=80
    container_name: rsplace_server